### PR TITLE
fix title : please review

### LINKED ISSUE #1: add feature A

### PR DESCRIPTION
**Pull request by GomaGoma676**
Closes #1

### CODE REVIEW

File: pages/index.js [hunk 1]
```diff
@@ -11,7 +11,7 @@ export default function Home() {
 
       <main className={styles.main}>
         <h1 className={styles.title}>
-          Welcome to <a href="https://nextjs.org">Next.js!</a>
+          Welcome to <a href="https://nextjs.org">Next.js CI!</a>
```
Comment (SleepingCats-KK) [inline pages/index.js:14]: LGTM

**Review by SleepingCats-KK — APPROVED** [review]
